### ISSUE TITLE
/data volume doesn't work

### ISSUE THREAD

**Issue by Pusnow** [linuxserver/docker-pydio#9]
When I upload some files, they are stored in `/config/www/pydio/data` not `/data`.
I think `/config/www/pydio/data` should be symlinked or something else to `/data`

This is my docker-compose.yml:
```

pydio:
  image: linuxserver/pydio
  ports:
   - "6500:443"
  links:
    - db
  volumes:
   - /mnt/data1/data/config:/config
   - /mnt/data1/data/data:/data

db:
  image: mariadb
  environment:
    - MYSQL_ROOT_PASSWORD=password
```
